### ISSUE TITLE
Support for casing options on Sql.ColumnNames

### ISSUE THREAD

**Issue by ELanning** [Faithlife/FaithlifeData#41]
`Sql.ColumnNames` is great, but it would be nice if there were a `casingKind` option such that I could chose

- PascalCase
- camelCase
- nocase
- other?

Currently only snake_case is supported I believe?

**Comment by ejball** [comment]
We currently assume two things:
* SQL is case-insensitive (so we don't bother distinguishing PascalCase, camelCase, and nocase)
* all tables in the same database use snake case or don't and can be [specified here](https://faithlife.github.io/FaithlifeData/#creating-a-connector)

If distinguishing PascalCase/camelCase/nocase is important to your scenario, or the connection-wide setting for snake_case isn't sufficient, please explain.

**Comment by ELanning** [comment]
The connection-wide setting is sufficient, but nonoptimal for "one off" situations. Legacy systems may have a mix of some snake, some pascal, or even new projects which cannot control the tables created by some 3rd party system.

Feel free to close this, but I do think it should be considered. The fact that PascalCase, camelCase, and nocase are equivalent in SQL also reduces the issue to a boolean snake_case or non snake_case, which is nice.
